# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Rails:
  Enabled: true

RSpec:
  Enabled: true

RSpec/IncludeExamples:
  Enabled: true


RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 10

Rails/I18nLocaleTexts:
  Enabled: false
